### ISSUE TITLE
vaultManager: true is not display Edit button for delete the added card ?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [Cretezy/braintree-web-drop-in-react#144]
Hi,

I Have added the code as below but i can't delete the card. Can you please help me

```
<DropIn
         options={{
          authorization: this.state.clientToken,
                   amount: "10.00",
                    vaultManager: true
            }}
           onInstance={instance => (this.instance = instance)}
/>
```

Thanks.

**Comment by Cretezy** [comment]
I'm not sure about the actual Braintree usage. This would be an upstream issue unfortuanately since this is just a wrapper around braintree-web-drop-in. This does look valid though, looking at the docs: https://developers.braintreepayments.com/guides/drop-in/customization/javascript/v3#delete-a-saved-payment-method
