### ISSUE TITLE
Is there a way to request to enter with credit card information instead of show previous credit card?

### ISSUE THREAD

**Issue by jbpadilha** [Cretezy/braintree-web-drop-in-react#26]
Is there a way to request to enter with credit card information instead of showing previous credit card?
I'd like to show the form every time, overwriting previous credit card setted before.

**Comment by Cretezy** [comment]
I don't know, but since this is a direct wrapper to their Drop-In library, check the [options](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create) to see if they offer this feature. Asking on [their repo](https://github.com/braintree/braintree-web-drop-in) is probably where you'd find the most help. Sorry!
